### ISSUE TITLE
Update the CHANGELOG

### ISSUE THREAD

**Issue by pdehaan** [mozilla/node-convict#120]
Re: https://github.com/mozilla/node-convict/issues/119#issuecomment-178632968

> we should really update the changelog one day https://github.com/mozilla/node-convict/blob/master/ChangeLog

---

We should probably just try and find a module that does a pretty changelog for us. It doesn't look like we're using Grunt or Gulp here, so adding that may be too much overhead. But it'd be nice to add auto-changelog generation on an npm prepublish hook or something.

**Comment by pdehaan** [comment]
We could possibly use [**changelog**](https://github.com/dylang/changelog). Not the prettiest, but doesn't seem to filter on commit messages or need any configs. Although oddly it only seems to be generating a changelog for 0.7.0->1.0.2 locally for me.

FWIW, I just added it as a devDep and then added this to my package.json `scripts` section:
```
"changelog": "changelog convict all --markdown > CHANGELOG.md"
```

Output is too much to paste here, but you can see it in this Gist: https://gist.github.com/pdehaan/949d5a757bae2d3cbe2c

**Comment by madarche** [comment]
@pdehaan: A fully automated process generating the changelog for us would not provide much quality I fear. Because there are many small commits that must be factored out into one, and issues that could be renamed/reworded too. *But* I would appreciate an automatic check (a `preversion` hook?) that bugs the developer if the `ChangeLog` when tagging if the file has not changed since the last tag. What do you think?
