### ISSUE TITLE
allowing "unknown" properties

### ISSUE THREAD

**Issue by jmls** [mozilla/node-convict#129]
I want my app to have a single config.json file - but in this file there may be other properties that the enduser can customise (ie I have no idea what they may be called, and may be added outside of the application)

Can I use convict in this manner ? The conf.load() seems to load the json file without errors, but if I try and get a property that is not in the schema, it fails with the message "Error: cannot find configuration param <nameofproperty>"

thanks

**Comment by jmls** [comment]
*bump* - anyone got an idea on how this may be possible ?

**Comment by madarche** [comment]
@jmls: that's the way convict has been designed. When in non-strict mode convict allows properties undefined in the schema to be present, but not to manipulate them, because manipulation is done through the schema. If you sometimes want to access custom properties without convict doing its job, you can read the config.json file through another mean.
