### ISSUE TITLE
JSON schema doesn't support built-in type format

### ISSUE THREAD

**Issue by damnhipster** [mozilla/node-convict#137]
```JSON
  // schema.json

  "assets": {
    "doc": "Asset information including path and extension",
    "format": "Array",
    "default": [
      {
        "type": "css",
        "path": "/css",
        "ext": ".css"
      }
    ]
  }
```

```javascript
// config.js
var schema = require('config/schema.json');
var conf = convict(schema);
```

I get the following error: 
```
Error: 'assets' uses an unknown format type: Array
```

It looks like `"Array"` being interpreted as a String rather than a built-in type.

Should I be doing this a different way?

**Comment by madarche** [comment]
Hello @damnhipster this is currently a limitation of defining the schema in JSON. If you define your schema programmatically through JavaScript and not JSON, using `"format": Array` instead of `"format": "Array"` it will work.

I find it very limiting too, but couldn't save any time to tackle it so far :-\

PR welcome!
