### ISSUE TITLE
Expose `types` in `module.exports`

### ISSUE THREAD

**Issue by foxx** [mozilla/node-convict#160]
I had an issue where I wanted to check for an "array of IPs", I used a custom format for this and wanted to reference the built in `types.ip`, but couldn't because it's not exposed via `module.exports`.

As such, I propose that we add `types` to the exports

**Comment by madarche** [comment]
Hello @foxx,
Since you are already writing a custom format, you can use the following code (that convict uses under the hood) to check for your "array of IPs":

```javascript
const validator = require('validator');
let res = validator.isIP(x);
```

That said I'm not against exposing the `types` to the outside, but if we do so we would have to make the exposed `types` read-only (to protect them). Not too difficult, but overkill if there isn't any strong usecase.

Thanks for using convict!

**Comment by foxx** [comment]
Closing this out, thanks for the quick reply!
